##
## Auto Generated makefile by CodeLite IDE
## any manual changes will be erased      
##
## Debug
ProjectName            :=ODSE_WO_RO
ConfigurationName      :=Debug
WorkspacePath          :=
ProjectPath            :=
IntermediateDirectory  :=./Debug
OutDir                 := $(IntermediateDirectory)
CurrentFileName        :=
CurrentFilePath        :=
CurrentFileFullPath    :=
User                   :=thanghoang
Date                   :=25/12/17
CodeLitePath           :=/home/thanghoang/.codelite
LinkerName             :=/usr/bin/g++
SharedObjectLinkerName :=/usr/bin/g++ -shared -fPIC
ObjectSuffix           :=.o
DependSuffix           :=.o.d
PreprocessSuffix       :=.i
DebugSwitch            :=-g 
IncludeSwitch          :=-I
LibrarySwitch          :=-l
OutputSwitch           :=-o 
LibraryPathSwitch      :=-L
PreprocessorSwitch     :=-D
SourceSwitch           :=-c 
OutputFile             :=$(IntermediateDirectory)/$(ProjectName)
Preprocessors          :=
ObjectSwitch           :=-o 
ArchiveOutputSwitch    := 
PreprocessOnlySwitch   :=-E
ObjectsFileList        :="ODSE_WO_RO.txt"
PCHCompileFlags        :=
MakeDirCommand         :=mkdir -p
LinkOptions            :=  -lzmq -lintel_aes64 -ltomcrypt -lpthread -lntl -lgmp 
IncludePath            :=  $(IncludeSwitch). $(IncludeSwitch). 
IncludePCH             := 
RcIncludePath          := 
Libs                   := 
ArLibs                 :=  
LibPath                := $(LibraryPathSwitch). $(LibraryPathSwitch)/usr/local/lib/ 

##
## Common variables
## AR, CXX, CC, AS, CXXFLAGS and CFLAGS can be overriden using an environment variables
##
AR       := /usr/bin/ar rcu
CXX      := /usr/bin/g++
CC       := /usr/bin/gcc
CXXFLAGS :=  -std=c++11  -libstdc++  -ggdb3 -c  -fmessage-length=0 -g -O0 -Wall -fPIC -MMD  -MP   -MF -lzmq  -lmsgpack  -lboost_iostreams
 $(Preprocessors)
CFLAGS   :=  -g -O0 -Wall $(Preprocessors)
ASFLAGS  := 
AS       := /usr/bin/as


##
## User defined environment variables
##
CodeLiteDir:=/usr/share/codelite
Objects0=$(IntermediateDirectory)/main.cpp$(ObjectSuffix) $(IntermediateDirectory)/Client_ODSE.cpp$(ObjectSuffix) $(IntermediateDirectory)/Keyword_Extraction.cpp$(ObjectSuffix) $(IntermediateDirectory)/Miscellaneous.cpp$(ObjectSuffix) $(IntermediateDirectory)/ODSE.cpp$(ObjectSuffix) $(IntermediateDirectory)/ODSE_Crypto.cpp$(ObjectSuffix) $(IntermediateDirectory)/Server_ODSE.cpp$(ObjectSuffix) $(IntermediateDirectory)/ODSE_Hashmap_Key_Class.cpp$(ObjectSuffix) $(IntermediateDirectory)/ODSE_KeyGen.cpp$(ObjectSuffix) $(IntermediateDirectory)/ODSE_Trapdoor.cpp$(ObjectSuffix) \
	



Objects=$(Objects0) 

##
## Main Build Targets 
##
.PHONY: all clean PreBuild PrePreBuild PostBuild MakeIntermediateDirs
all: $(OutputFile)

$(OutputFile): $(IntermediateDirectory)/.d $(Objects) 
	@$(MakeDirCommand) $(@D)
	@echo "" > $(IntermediateDirectory)/.d
	@echo $(Objects0)  > $(ObjectsFileList)
	$(LinkerName) $(OutputSwitch)$(OutputFile) @$(ObjectsFileList) $(LibPath) $(Libs) $(LinkOptions)

MakeIntermediateDirs:
	@test -d ./Debug || $(MakeDirCommand) ./Debug


$(IntermediateDirectory)/.d:
	@test -d ./Debug || $(MakeDirCommand) ./Debug

PreBuild:


##
## Objects
##
$(IntermediateDirectory)/main.cpp$(ObjectSuffix): main.cpp $(IntermediateDirectory)/main.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "main.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/main.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/main.cpp$(DependSuffix): main.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/main.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/main.cpp$(DependSuffix) -MM main.cpp

$(IntermediateDirectory)/main.cpp$(PreprocessSuffix): main.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/main.cpp$(PreprocessSuffix) main.cpp

$(IntermediateDirectory)/Client_ODSE.cpp$(ObjectSuffix): Client_ODSE.cpp $(IntermediateDirectory)/Client_ODSE.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "Client_ODSE.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/Client_ODSE.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/Client_ODSE.cpp$(DependSuffix): Client_ODSE.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/Client_ODSE.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/Client_ODSE.cpp$(DependSuffix) -MM Client_ODSE.cpp

$(IntermediateDirectory)/Client_ODSE.cpp$(PreprocessSuffix): Client_ODSE.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/Client_ODSE.cpp$(PreprocessSuffix) Client_ODSE.cpp

$(IntermediateDirectory)/Keyword_Extraction.cpp$(ObjectSuffix): Keyword_Extraction.cpp $(IntermediateDirectory)/Keyword_Extraction.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "Keyword_Extraction.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/Keyword_Extraction.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/Keyword_Extraction.cpp$(DependSuffix): Keyword_Extraction.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/Keyword_Extraction.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/Keyword_Extraction.cpp$(DependSuffix) -MM Keyword_Extraction.cpp

$(IntermediateDirectory)/Keyword_Extraction.cpp$(PreprocessSuffix): Keyword_Extraction.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/Keyword_Extraction.cpp$(PreprocessSuffix) Keyword_Extraction.cpp

$(IntermediateDirectory)/Miscellaneous.cpp$(ObjectSuffix): Miscellaneous.cpp $(IntermediateDirectory)/Miscellaneous.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "Miscellaneous.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/Miscellaneous.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/Miscellaneous.cpp$(DependSuffix): Miscellaneous.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/Miscellaneous.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/Miscellaneous.cpp$(DependSuffix) -MM Miscellaneous.cpp

$(IntermediateDirectory)/Miscellaneous.cpp$(PreprocessSuffix): Miscellaneous.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/Miscellaneous.cpp$(PreprocessSuffix) Miscellaneous.cpp

$(IntermediateDirectory)/ODSE.cpp$(ObjectSuffix): ODSE.cpp $(IntermediateDirectory)/ODSE.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "ODSE.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/ODSE.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/ODSE.cpp$(DependSuffix): ODSE.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/ODSE.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/ODSE.cpp$(DependSuffix) -MM ODSE.cpp

$(IntermediateDirectory)/ODSE.cpp$(PreprocessSuffix): ODSE.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/ODSE.cpp$(PreprocessSuffix) ODSE.cpp

$(IntermediateDirectory)/ODSE_Crypto.cpp$(ObjectSuffix): ODSE_Crypto.cpp $(IntermediateDirectory)/ODSE_Crypto.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "ODSE_Crypto.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/ODSE_Crypto.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/ODSE_Crypto.cpp$(DependSuffix): ODSE_Crypto.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/ODSE_Crypto.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/ODSE_Crypto.cpp$(DependSuffix) -MM ODSE_Crypto.cpp

$(IntermediateDirectory)/ODSE_Crypto.cpp$(PreprocessSuffix): ODSE_Crypto.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/ODSE_Crypto.cpp$(PreprocessSuffix) ODSE_Crypto.cpp

$(IntermediateDirectory)/Server_ODSE.cpp$(ObjectSuffix): Server_ODSE.cpp $(IntermediateDirectory)/Server_ODSE.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "Server_ODSE.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/Server_ODSE.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/Server_ODSE.cpp$(DependSuffix): Server_ODSE.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/Server_ODSE.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/Server_ODSE.cpp$(DependSuffix) -MM Server_ODSE.cpp

$(IntermediateDirectory)/Server_ODSE.cpp$(PreprocessSuffix): Server_ODSE.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/Server_ODSE.cpp$(PreprocessSuffix) Server_ODSE.cpp

$(IntermediateDirectory)/ODSE_Hashmap_Key_Class.cpp$(ObjectSuffix): ODSE_Hashmap_Key_Class.cpp $(IntermediateDirectory)/ODSE_Hashmap_Key_Class.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "ODSE_Hashmap_Key_Class.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/ODSE_Hashmap_Key_Class.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/ODSE_Hashmap_Key_Class.cpp$(DependSuffix): ODSE_Hashmap_Key_Class.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/ODSE_Hashmap_Key_Class.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/ODSE_Hashmap_Key_Class.cpp$(DependSuffix) -MM ODSE_Hashmap_Key_Class.cpp

$(IntermediateDirectory)/ODSE_Hashmap_Key_Class.cpp$(PreprocessSuffix): ODSE_Hashmap_Key_Class.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/ODSE_Hashmap_Key_Class.cpp$(PreprocessSuffix) ODSE_Hashmap_Key_Class.cpp

$(IntermediateDirectory)/ODSE_KeyGen.cpp$(ObjectSuffix): ODSE_KeyGen.cpp $(IntermediateDirectory)/ODSE_KeyGen.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "ODSE_KeyGen.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/ODSE_KeyGen.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/ODSE_KeyGen.cpp$(DependSuffix): ODSE_KeyGen.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/ODSE_KeyGen.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/ODSE_KeyGen.cpp$(DependSuffix) -MM ODSE_KeyGen.cpp

$(IntermediateDirectory)/ODSE_KeyGen.cpp$(PreprocessSuffix): ODSE_KeyGen.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/ODSE_KeyGen.cpp$(PreprocessSuffix) ODSE_KeyGen.cpp

$(IntermediateDirectory)/ODSE_Trapdoor.cpp$(ObjectSuffix): ODSE_Trapdoor.cpp $(IntermediateDirectory)/ODSE_Trapdoor.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "ODSE_Trapdoor.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/ODSE_Trapdoor.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/ODSE_Trapdoor.cpp$(DependSuffix): ODSE_Trapdoor.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/ODSE_Trapdoor.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/ODSE_Trapdoor.cpp$(DependSuffix) -MM ODSE_Trapdoor.cpp

$(IntermediateDirectory)/ODSE_Trapdoor.cpp$(PreprocessSuffix): ODSE_Trapdoor.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/ODSE_Trapdoor.cpp$(PreprocessSuffix) ODSE_Trapdoor.cpp


-include $(IntermediateDirectory)/*$(DependSuffix)
##
## Clean
##
clean:
	$(RM) -r ./Debug/


