.PHONY: clean All

All:
	@echo "----------Building project:[ ODSE_WO_IT - Debug ]----------"
	@cd "ODSE_WO_IT" && "$(MAKE)" -f  "ODSE_WO_IT.mk"
clean:
	@echo "----------Cleaning project:[ ODSE_WO_IT - Debug ]----------"
	@cd "ODSE_WO_IT" && "$(MAKE)" -f  "ODSE_WO_IT.mk" clean
