.PHONY: clean All

All:
	@echo "----------Building project:[ ODSE_WO_XOR - Debug ]----------"
	@cd "ODSE_WO_XOR" && "$(MAKE)" -f  "ODSE_WO_XOR.mk"
clean:
	@echo "----------Cleaning project:[ ODSE_WO_XOR - Debug ]----------"
	@cd "ODSE_WO_XOR" && "$(MAKE)" -f  "ODSE_WO_XOR.mk" clean
