.PHONY: clean All

All:
	@echo "----------Building project:[ ODSE_WO_RO - Debug ]----------"
	@cd "ODSE_WO_RO" && "$(MAKE)" -f  "ODSE_WO_RO.mk"
clean:
	@echo "----------Cleaning project:[ ODSE_WO_RO - Debug ]----------"
	@cd "ODSE_WO_RO" && "$(MAKE)" -f  "ODSE_WO_RO.mk" clean
