.PHONY: clean All

All:
	@echo "----------Building project:[ ODSE_RO_WO - Debug ]----------"
	@cd "ODSE_RO_WO" && "$(MAKE)" -f  "ODSE_RO_WO.mk"
clean:
	@echo "----------Cleaning project:[ ODSE_RO_WO - Debug ]----------"
	@cd "ODSE_RO_WO" && "$(MAKE)" -f  "ODSE_RO_WO.mk" clean
