.PHONY: clean All

All:
	@echo "----------Building project:[ ODSE_xor_wo - Debug ]----------"
	@cd "ODSE_XOR_WO" && "$(MAKE)" -f  "ODSE_xor_wo.mk"
clean:
	@echo "----------Cleaning project:[ ODSE_xor_wo - Debug ]----------"
	@cd "ODSE_XOR_WO" && "$(MAKE)" -f  "ODSE_xor_wo.mk" clean
